### ISSUE TITLE
Installing @applitools/eyes-selenium leads to duplicated @applitools/eyes-common

### ISSUE THREAD

**Issue by ZauberNerd** [applitools/eyes.sdk.javascript1#127]
Installing `@applitools/eyes-selenium@4.33.24` leads to `@applitools/eyes-common` being installed in multiple version.

```
 /tmp/foo $ yarn list --pattern "applitools"
yarn list v1.22.0
├─ @applitools/dom-capture@7.1.3
├─ @applitools/dom-snapshot@3.3.3
├─ @applitools/dom-utils@4.7.7
│  └─ @applitools/eyes-common@3.19.0
├─ @applitools/eyes-common@3.20.0
├─ @applitools/eyes-sdk-core@8.1.1
├─ @applitools/eyes-selenium@4.33.24
│  └─ @applitools/eyes-common@3.20.1
├─ @applitools/functional-commons@1.5.5
├─ @applitools/http-commons@2.3.12
├─ @applitools/isomorphic-fetch@3.0.0
├─ @applitools/jsdom@1.0.2
├─ @applitools/monitoring-commons@1.0.19
└─ @applitools/visual-grid-client@13.6.0
   └─ @applitools/functional-commons@1.5.4
Done in 0.16s.
```

Which leads to the following error when executing tests:

```
[2020-03-08T23:33:51.370Z]      Error: IllegalType: x is not a number
[2020-03-08T23:33:51.370Z]       at Function.isNumber (/app/node_modules/@applitools/eyes-selenium/node_modules/@applitools/eyes-common/lib/utils/ArgumentGuard.js:158:13)
[2020-03-08T23:33:51.370Z]       at new Location (/app/node_modules/@applitools/eyes-selenium/node_modules/@applitools/eyes-common/lib/geometry/Location.js:39:19)
[2020-03-08T23:33:51.370Z]       at EyesWebDriverScreenshot.convertLocation (/app/node_modules/@applitools/eyes-selenium/lib/capture/EyesWebDriverScreenshot.js:431:18)
[2020-03-08T23:33:51.370Z]       at EyesWebDriverScreenshot.convertRegionLocation (/app/node_modules/@applitools/eyes-sdk-core/lib/capture/EyesScreenshot.js:95:34)
[2020-03-08T23:33:51.370Z]       at EyesWebDriverScreenshot.getIntersectedRegion (/app/node_modules/@applitools/eyes-selenium/lib/capture/EyesWebDriverScreenshot.js:605:30)
[2020-03-08T23:33:51.370Z]       at FullPageCaptureAlgorithm._getRegionInScreenshot (/app/node_modules/@applitools/eyes-sdk-core/lib/capture/FullPageCaptureAlgorithm.js:358:41)
[2020-03-08T23:33:51.370Z]       at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2020-03-08T23:33:51.370Z]       at async FullPageCaptureAlgorithm.getStitchedRegion (/app/node_modules/@applitools/eyes-sdk-core/lib/capture/FullPageCaptureAlgorithm.js:119:32)
[2020-03-08T23:33:51.370Z]       at async EyesSelenium._getFullPageScreenshot (/app/node_modules/@applitools/eyes-selenium/lib/EyesSelenium.js:1201:27)
[2020-03-08T23:33:51.370Z]       at async EyesSelenium.getScreenshot (/app/node_modules/@applitools/eyes-selenium/lib/EyesSelenium.js:1064:16)
[2020-03-08T23:33:51.370Z]       at async EyesSelenium._getAppOutputWithScreenshot (/app/node_modules/@applitools/eyes-sdk-core/lib/EyesBase.js:2127:18)
[2020-03-08T23:33:51.370Z]       at async MatchWindowTask._tryTakeScreenshot (/app/node_modules/@applitools/eyes-sdk-core/lib/MatchWindowTask.js:438:23)
[2020-03-08T23:33:51.370Z]       at async MatchWindowTask._takingScreenshotLoop (/app/node_modules/@applitools/eyes-sdk-core/lib/MatchWindowTask.js:401:27)
[2020-03-08T23:33:51.370Z]       at async MatchWindowTask._retryTakingScreenshot (/app/node_modules/@applitools/eyes-sdk-core/lib/MatchWindowTask.js:350:24)
[2020-03-08T23:33:51.370Z]       at async MatchWindowTask._takeScreenshot (/app/node_modules/@applitools/eyes-sdk-core/lib/MatchWindowTask.js:312:20)
[2020-03-08T23:33:51.370Z]       at async MatchWindowTask.matchWindow (/app/node_modules/@applitools/eyes-sdk-core/lib/MatchWindowTask.js:253:24)
[2020-03-08T23:33:51.370Z]       at async EyesSelenium.checkWindowBase (/app/node_modules/@applitools/eyes-sdk-core/lib/EyesBase.js:1333:25)
[2020-03-08T23:33:51.370Z]       at async EyesSelenium.check (/app/node_modules/@applitools/eyes-selenium/lib/EyesSelenium.js:269:18)
[2020-03-08T23:33:51.370Z]       at async Context.<anonymous> (spec/files/crate-redux.js:67:7)
```

De-duplicating `@applitools/eyes-common` by pinning it to `3.20.1` through yarn resolutions fixes the issue.

**Comment by tourdedave** [comment]
Thanks for the heads up. This should be fixed in `eyes-selenium@4.33.26`.
