### ISSUE TITLE
"versionMatch.group is not a function" on Safari

### ISSUE THREAD

**Issue by klamping** [applitools/eyes.sdk.javascript1#24]
When running tests through "eyes.webdriverio.javascript", I get the following message:
```
TypeError: versionMatch.group is not a function
    at Function.parseUserAgentString (/Users/klamping/Sites/wdio-applitools-service/node_modules/@applitools/eyes.sdk.core/lib/utils/UserAgent.js:178:50)
    at Eyes.open (/Users/klamping/Sites/wdio-applitools-service/node_modules/@applitools/eyes.webdriverio/lib/Eyes.js:138:35)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```
I've tracked it back to this line of code:
https://github.com/applitools/eyes.sdk.javascript1/blob/251b1ee223784ef2c1b1cdb0ff257155d7c172cc/eyes.sdk.core/lib/utils/UserAgent.js#L178

This only happens for Safari, not Chrome or Firefox.

**Comment by danielputerman** [comment]
Fixed in d49802b14e6fa123739dc8e8de6d3b36c864c918. Fix is already available in version 1.6.0 in npm.
