### ISSUE TITLE
eyes-cypress unable to use cy.route2

### ISSUE THREAD

**Issue by tiagodread** [applitools/eyes.sdk.javascript1#353]
Summary:

Trying to use cy.route2 modifying the response, using `eyes-cypress": "^3.18.2"` I get `[server] error in eyes api: Error: Please call cy.eyesOpen() before calling cy.eyesCheckWindow()` on console log and the test run doesn't appear on applitools dashboard page.

**The same tests works fine using `"@applitools/eyes-cypress": "^3.13.4"`, modify the response and appear on applitools dashboard.** 

Environment:

- "@applitools/eyes-cypress": "^3.18.2",
- "cypress": "5.3.0",

Test:

```
context('Visual Testing - Templates', function () {
  beforeEach(() => {
    cy.eyesOpen()
  })
  afterEach(() => {
    cy.eyesClose()
  })

  it('JT add form - Inventory modal', function () {
    cy.route2('GET', '/api/v2/inventories/?order_by=name&page=1&page_size=5', (req) => {
      req.reply((res) => {
        expect(res.body).to.exist
        const modified_body = JSON.parse(res.body)
        modified_body.results.forEach((obj, index) => {
          obj.name = `Inventory - ${index}`
        })
        res.send(modified_body)
      })
    })
    cy.visit('/#/templates/job_template/add')
    cy.get('#inventory-lookup').click()
    cy.get('div[aria-label="Lookup modal"]').should('be.visible')
    cy.eyesCheckWindow('JT-Add-Form-Inventory-Modal')
  })
})
```

Full console Log when `cy.eyesCheckWindow` function is called:

````
2021-01-13T12:24:50Z Eyes: [LOG    ] {} (): [server] eyes api: checkWindow [url,snapshot,browser,tag]
2021-01-13T12:24:50Z Eyes: [LOG    ] {} Object.checkWindow(): [handlers] checkWindow: checkWindow=object
2021-01-13T12:24:50Z Eyes: [LOG    ] {} (): [server] error in eyes api: Error: Please call cy.eyesOpen() before calling cy.eyesCheckWindow()
    at Object.checkWindow (/Users/tisilva/Redhat/tower-qa/ui-tests/awx-pf-tests/node_modules/@applitools/eyes-cypress/src/plugin/handlers.js:128:15)
    at /Users/tisilva/Redhat/tower-qa/ui-tests/awx-pf-tests/node_modules/@applitools/eyes-cypress/src/plugin/app.js:30:56
    at Layer.handle [as handle_request] (/Users/tisilva/Redhat/tower-qa/ui-tests/awx-pf-tests/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/tisilva/Redhat/tower-qa/ui-tests/awx-pf-tests/node_modules/express/lib/router/route.js:137:13)
    at /Users/tisilva/Redhat/tower-qa/ui-tests/awx-pf-tests/node_modules/body-parser/lib/read.js:130:5
    at invokeCallback (/Users/tisilva/Redhat/tower-qa/ui-tests/awx-pf-tests/node_modules/raw-body/index.js:224:16)
    at done (/Users/tisilva/Redhat/tower-qa/ui-tests/awx-pf-tests/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/Users/tisilva/Redhat/tower-qa/ui-tests/awx-pf-tests/node_modules/raw-body/index.js:273:7)
    at IncomingMessage.emit (events.js:228:7)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)

**Comment by amitzur** [comment]
Hi @tiagodread ,

This is an old issue, so hopefully it is resolved by now.
For feature requests, feedback, and bug reports, please contact support@applitools.com
