### ISSUE TITLE
eyes-cypress plugin crashed when run test

### ISSUE THREAD

**Issue by lliu32** [applitools/eyes.sdk.javascript1#358]
Followed the [Applitools Cypress plugin official tutorial](https://github.com/applitools/tutorial-cypress) and run the example test, the plugin throw following error and the test cannot be done. Any ideas? Thanks.

``` 
AppTest

The following error was thrown by a plugin. We stopped running your tests because a plugin crashed. Please check your plugins file (`/Users/Shared/tmp/tutorial-cypress/cypress/plugins/index.js`)

 TypeError: Cannot read property 'endsWith' of undefined
    at stripTrailingSlash (/Users/Shared/tmp/tutorial-cypress/node_modules/@applitools/eyes-sdk-core/lib/utils/GeneralUtils.js:43:14)
    at Object.urlConcat (/Users/Shared/tmp/tutorial-cypress/node_modules/@applitools/eyes-sdk-core/lib/utils/GeneralUtils.js:22:19)
    at ServerConnector.renderCheckResources (/Users/Shared/tmp/tutorial-cypress/node_modules/@applitools/eyes-sdk-core/lib/server/ServerConnector.js:642:25)
    at EyesWrapper.checkResources (/Users/Shared/tmp/tutorial-cypress/node_modules/@applitools/visual-grid-client/src/sdk/EyesWrapper.js:132:34)
    at putResources (/Users/Shared/tmp/tutorial-cypress/node_modules/@applitools/visual-grid-client/src/sdk/putResources.js:68:40)
    at Timeout._onTimeout (/Users/Shared/tmp/tutorial-cypress/node_modules/@applitools/visual-grid-client/src/sdk/putResources.js:49:9)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

```

Versions:
eyes-cypress: 3.18.4
cypress: 6.2.1

**Comment by tool3** [comment]
@lliu32 this shouldn't happen anymore but if it does please send an email to support@applitools.com and we'll be happy to assist
