### ISSUE TITLE
getSize is not a function

### ISSUE THREAD

**Issue by au-top** [applitools/eyes.sdk.javascript1#364]
```

const getElem = async (d: WebDriver, l: Locator) => {
  return await d.wait(d.findElement(l), waitTime);
};
  const CanvaSize=await (await getElem(driver, By.css('#game'))).getSize();

```

(node:4084) UnhandledPromiseRejectionWarning: TypeError: _context4.sent.getSize is not a function
    at _callee4$ (D:\project\js\quanquan\dist\index.js:179:35)
    at tryCatch (D:\project\js\quanquan\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\project\js\quanquan\node_modules\regenerator-runtime\runtime.js:293:22)
    at Generator.next (D:\project\js\quanquan\node_modules\regenerator-runtime\runtime.js:118:21)
    at asyncGeneratorStep (D:\project\js\quanquan\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\project\js\quanquan\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by au-top** [comment]
my package.json
```

{
  "name": "newApp",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@babel/cli": "^7.12.1",
    "@babel/core": "^7.12.3",
    "@babel/plugin-proposal-class-properties": "^7.12.1",
    "@babel/plugin-transform-runtime": "^7.12.1",
    "@babel/preset-env": "^7.12.1",
    "@babel/preset-typescript": "^7.12.1",
    "@types/node": "^14.14.20",
    "@types/selenium-webdriver": "^4.0.11",
    "@typescript-eslint/eslint-plugin": "^4.14.0",
    "@typescript-eslint/parser": "^4.14.0",
    "eslint": "^7.17.0",
    "typescript": "^4.0.5"
  },
  "dependencies": {
    "selenium-webdriver": "^4.0.0-alpha.8"
  }
}


```

**Comment by amitzur** [comment]
@au-top I believe this is the wrong repo to file this issue. We handle Applitools JavaScript SDK issues. If you encounter any issue with our service, feel free to reach out to support@applitools.com
