### ISSUE TITLE
Can't run tests when including the @applitools/eyes-cypress/commands package

### ISSUE THREAD

**Issue by joelsjostrom** [applitools/eyes.sdk.javascript1#380]
os: macos bigSur
node version: 14

Since a while back I'm not able to run my cypress tests whatsoever if i include: 

`import "@applitools/eyes-cypress/commands";
`

in either cypress/support/index.js or cypress/support/commands.ts

When I try to run the tests I get the following error in the cypress test runner:

cypress_runner.js:201315 TypeError: Failed to execute 'fetch' on 'Window': Failed to parse URL from https://localhost:undefined/eyes/batchStart

Because this error occurred during a `before all` hook we are skipping all of the remaining tests.
    at send (http://localhost:9001/__cypress/tests?p=cypress/support/index.js:1394:12)
    at sendRequest (http://localhost:9001/__cypress/tests?p=cypress/support/index.js:1456:12)
    at Context.eval (http://localhost:9001/__cypress/tests?p=cypress/support/index.js:1049:7)
From previous event:
    at Context.thenFn (http://localhost:9001/__cypress/runner/cypress_runner.js:155561:23)
    at Context.then (http://localhost:9001/__cypress/runner/cypress_runner.js:156000:21)
    at Context.<anonymous> (http://localhost:9001/__cypress/runner/cypress_runner.js:170619:21)
    at http://localhost:9001/__cypress/runner/cypress_runner.js:170043:15
From previous event:
    at runCommand (http://localhost:9001/__cypress/runner/cypress_runner.js:170022:8)
    at next (http://localhost:9001/__cypress/runner/cypress_runner.js:170168:14)
From previous event:
    at Promise.catch.err.name (http://localhost:9001/__cypress/runner/cypress_runner.js:170209:37)
From previous event:
    at run (http://localhost:9001/__cypress/runner/cypress_runner.js:170202:21)
    at $Cy.cy.<computed> [as then] (http://localhost:9001/__cypress/runner/cypress_runner.js:170659:11)
    at Context.runnable.fn (http://localhost:9001/__cypress/runner/cypress_runner.js:170886:21)
    at callFn (http://localhost:9001/__cypress/runner/cypress_runner.js:104252:21)
    at Hook.../driver/node_modules/mocha/lib/runnable.js.Runnable.run (http://localhost:9001/__cypress/runner/cypress_runner.js:104239:7)
    at http://localhost:9001/__cypress/runner/cypress_runner.js:176660:28
From previous event:
    at Object.onRunnableRun (http://localhost:9001/__cypress/runner/cypress_runner.js:176648:17)
    at $Cypress.action (http://localhost:9001/__cypress/runner/cypress_runner.js:167027:28)
    at Hook.Runnable.run (http://localhost:9001/__cypress/runner/cypress_runner.js:174825:13)
    at next (http://localhost:9001/__cypress/runner/cypress_runner.js:104754:10)
    at http://localhost:9001/__cypress/runner/cypress_runner.js:104798:5
    at timeslice (http://localhost:9001/__cypress/runner/cypress_runner.js:98724:27)

**Comment by tourdedave** [comment]
Hey @joelsjostrom, sorry to hear that. Please email support@applitools.com.

Thanks!

**Comment by Alpsli** [comment]
I have the same issue: Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'Window': Failed to parse URL from https://localhost:undefined/eyes/batchStart
    at send (tests?p=cypress/support/index.js-724:2949)
    at sendRequest (tests?p=cypress/support/index.js-724:2991)
    at Context.<anonymous> (tests?p=cypress/support/index.js-724:2620)

**Comment by jspkiel** [comment]
Similar situation here as well

![Screenshot 2021-04-04 at 04 05 42](https://user-images.githubusercontent.com/12475983/113497342-13833480-94fb-11eb-9ef0-df93f275c2ea.png)
